package com.wk.cpd.mvc.dao.model;

public class DspInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_info.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_info.ipv4
     *
     * @mbg.generated
     */
    private String ipv4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_info.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_info.link_num
     *
     * @mbg.generated
     */
    private Integer linkNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_info.id
     *
     * @return the value of dsp_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_info.id
     *
     * @param id the value for dsp_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_info.url
     *
     * @return the value of dsp_info.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_info.url
     *
     * @param url the value for dsp_info.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_info.ipv4
     *
     * @return the value of dsp_info.ipv4
     *
     * @mbg.generated
     */
    public String getIpv4() {
        return ipv4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_info.ipv4
     *
     * @param ipv4 the value for dsp_info.ipv4
     *
     * @mbg.generated
     */
    public void setIpv4(String ipv4) {
        this.ipv4 = ipv4 == null ? null : ipv4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_info.port
     *
     * @return the value of dsp_info.port
     *
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_info.port
     *
     * @param port the value for dsp_info.port
     *
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_info.link_num
     *
     * @return the value of dsp_info.link_num
     *
     * @mbg.generated
     */
    public Integer getLinkNum() {
        return linkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_info.link_num
     *
     * @param linkNum the value for dsp_info.link_num
     *
     * @mbg.generated
     */
    public void setLinkNum(Integer linkNum) {
        this.linkNum = linkNum;
    }
}