package com.wk.cpd.mvc.dao.model;

public class Plat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat.mtime
     *
     * @mbg.generated
     */
    private Integer mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat.id
     *
     * @return the value of tb_plat.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat.id
     *
     * @param id the value for tb_plat.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat.name
     *
     * @return the value of tb_plat.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat.name
     *
     * @param name the value for tb_plat.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat.ctime
     *
     * @return the value of tb_plat.ctime
     *
     * @mbg.generated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat.ctime
     *
     * @param ctime the value for tb_plat.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat.mtime
     *
     * @return the value of tb_plat.mtime
     *
     * @mbg.generated
     */
    public Integer getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat.mtime
     *
     * @param mtime the value for tb_plat.mtime
     *
     * @mbg.generated
     */
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }
}