package com.wk.cpd.mvc.dao.model;

import java.math.BigDecimal;

public class PlatUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat_user.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat_user.plat_id
     *
     * @mbg.generated
     */
    private Integer platId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat_user.plat_username
     *
     * @mbg.generated
     */
    private String platUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat_user.plat_password
     *
     * @mbg.generated
     */
    private String platPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat_user.plat_balance
     *
     * @mbg.generated
     */
    private BigDecimal platBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat_user.plat_company
     *
     * @mbg.generated
     */
    private String platCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat_user.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plat_user.mtime
     *
     * @mbg.generated
     */
    private Integer mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat_user.id
     *
     * @return the value of tb_plat_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat_user.id
     *
     * @param id the value for tb_plat_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat_user.uid
     *
     * @return the value of tb_plat_user.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat_user.uid
     *
     * @param uid the value for tb_plat_user.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat_user.plat_id
     *
     * @return the value of tb_plat_user.plat_id
     *
     * @mbg.generated
     */
    public Integer getPlatId() {
        return platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat_user.plat_id
     *
     * @param platId the value for tb_plat_user.plat_id
     *
     * @mbg.generated
     */
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat_user.plat_username
     *
     * @return the value of tb_plat_user.plat_username
     *
     * @mbg.generated
     */
    public String getPlatUsername() {
        return platUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat_user.plat_username
     *
     * @param platUsername the value for tb_plat_user.plat_username
     *
     * @mbg.generated
     */
    public void setPlatUsername(String platUsername) {
        this.platUsername = platUsername == null ? null : platUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat_user.plat_password
     *
     * @return the value of tb_plat_user.plat_password
     *
     * @mbg.generated
     */
    public String getPlatPassword() {
        return platPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat_user.plat_password
     *
     * @param platPassword the value for tb_plat_user.plat_password
     *
     * @mbg.generated
     */
    public void setPlatPassword(String platPassword) {
        this.platPassword = platPassword == null ? null : platPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat_user.plat_balance
     *
     * @return the value of tb_plat_user.plat_balance
     *
     * @mbg.generated
     */
    public BigDecimal getPlatBalance() {
        return platBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat_user.plat_balance
     *
     * @param platBalance the value for tb_plat_user.plat_balance
     *
     * @mbg.generated
     */
    public void setPlatBalance(BigDecimal platBalance) {
        this.platBalance = platBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat_user.plat_company
     *
     * @return the value of tb_plat_user.plat_company
     *
     * @mbg.generated
     */
    public String getPlatCompany() {
        return platCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat_user.plat_company
     *
     * @param platCompany the value for tb_plat_user.plat_company
     *
     * @mbg.generated
     */
    public void setPlatCompany(String platCompany) {
        this.platCompany = platCompany == null ? null : platCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat_user.ctime
     *
     * @return the value of tb_plat_user.ctime
     *
     * @mbg.generated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat_user.ctime
     *
     * @param ctime the value for tb_plat_user.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plat_user.mtime
     *
     * @return the value of tb_plat_user.mtime
     *
     * @mbg.generated
     */
    public Integer getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plat_user.mtime
     *
     * @param mtime the value for tb_plat_user.mtime
     *
     * @mbg.generated
     */
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }
}