package com.wk.cpd.mvc.dao.model;

import java.math.BigDecimal;

public class PromotionPriceHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_price_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_price_log.plat_id
     *
     * @mbg.generated
     */
    private Integer platId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_price_log.plat_promotion_id
     *
     * @mbg.generated
     */
    private String platPromotionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_price_log.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_price_log.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_price_log.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_price_log.mtime
     *
     * @mbg.generated
     */
    private Integer mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_price_log.id
     *
     * @return the value of tb_promotion_price_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_price_log.id
     *
     * @param id the value for tb_promotion_price_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_price_log.plat_id
     *
     * @return the value of tb_promotion_price_log.plat_id
     *
     * @mbg.generated
     */
    public Integer getPlatId() {
        return platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_price_log.plat_id
     *
     * @param platId the value for tb_promotion_price_log.plat_id
     *
     * @mbg.generated
     */
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_price_log.plat_promotion_id
     *
     * @return the value of tb_promotion_price_log.plat_promotion_id
     *
     * @mbg.generated
     */
    public String getPlatPromotionId() {
        return platPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_price_log.plat_promotion_id
     *
     * @param platPromotionId the value for tb_promotion_price_log.plat_promotion_id
     *
     * @mbg.generated
     */
    public void setPlatPromotionId(String platPromotionId) {
        this.platPromotionId = platPromotionId == null ? null : platPromotionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_price_log.type
     *
     * @return the value of tb_promotion_price_log.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_price_log.type
     *
     * @param type the value for tb_promotion_price_log.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_price_log.price
     *
     * @return the value of tb_promotion_price_log.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_price_log.price
     *
     * @param price the value for tb_promotion_price_log.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_price_log.ctime
     *
     * @return the value of tb_promotion_price_log.ctime
     *
     * @mbg.generated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_price_log.ctime
     *
     * @param ctime the value for tb_promotion_price_log.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_price_log.mtime
     *
     * @return the value of tb_promotion_price_log.mtime
     *
     * @mbg.generated
     */
    public Integer getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_price_log.mtime
     *
     * @param mtime the value for tb_promotion_price_log.mtime
     *
     * @mbg.generated
     */
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }
}