package com.wk.cpd.mvc.dao.model;

import java.math.BigDecimal;

public class Promotion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.plat_id
     *
     * @mbg.generated
     */
    private Integer platId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.plat_username
     *
     * @mbg.generated
     */
    private String platUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.plat_app_id
     *
     * @mbg.generated
     */
    private String platAppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.plat_promotion_id
     *
     * @mbg.generated
     */
    private String platPromotionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.plat_app_icon
     *
     * @mbg.generated
     */
    private String platAppIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.plat_app_name
     *
     * @mbg.generated
     */
    private String platAppName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.plat_app_package_name
     *
     * @mbg.generated
     */
    private String platAppPackageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.plat_promotion_name
     *
     * @mbg.generated
     */
    private String platPromotionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.app_price
     *
     * @mbg.generated
     */
    private BigDecimal appPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.search_price
     *
     * @mbg.generated
     */
    private BigDecimal searchPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.star
     *
     * @mbg.generated
     */
    private Integer star;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.total_limit
     *
     * @mbg.generated
     */
    private BigDecimal totalLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.app_daily_budget
     *
     * @mbg.generated
     */
    private BigDecimal appDailyBudget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.search_daily_budget
     *
     * @mbg.generated
     */
    private BigDecimal searchDailyBudget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.app_regular_change_price
     *
     * @mbg.generated
     */
    private Byte appRegularChangePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.search_regular_change_price
     *
     * @mbg.generated
     */
    private Byte searchRegularChangePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion.mtime
     *
     * @mbg.generated
     */
    private Integer mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.id
     *
     * @return the value of tb_promotion.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.id
     *
     * @param id the value for tb_promotion.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.uid
     *
     * @return the value of tb_promotion.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.uid
     *
     * @param uid the value for tb_promotion.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.plat_id
     *
     * @return the value of tb_promotion.plat_id
     *
     * @mbg.generated
     */
    public Integer getPlatId() {
        return platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.plat_id
     *
     * @param platId the value for tb_promotion.plat_id
     *
     * @mbg.generated
     */
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.plat_username
     *
     * @return the value of tb_promotion.plat_username
     *
     * @mbg.generated
     */
    public String getPlatUsername() {
        return platUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.plat_username
     *
     * @param platUsername the value for tb_promotion.plat_username
     *
     * @mbg.generated
     */
    public void setPlatUsername(String platUsername) {
        this.platUsername = platUsername == null ? null : platUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.plat_app_id
     *
     * @return the value of tb_promotion.plat_app_id
     *
     * @mbg.generated
     */
    public String getPlatAppId() {
        return platAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.plat_app_id
     *
     * @param platAppId the value for tb_promotion.plat_app_id
     *
     * @mbg.generated
     */
    public void setPlatAppId(String platAppId) {
        this.platAppId = platAppId == null ? null : platAppId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.plat_promotion_id
     *
     * @return the value of tb_promotion.plat_promotion_id
     *
     * @mbg.generated
     */
    public String getPlatPromotionId() {
        return platPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.plat_promotion_id
     *
     * @param platPromotionId the value for tb_promotion.plat_promotion_id
     *
     * @mbg.generated
     */
    public void setPlatPromotionId(String platPromotionId) {
        this.platPromotionId = platPromotionId == null ? null : platPromotionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.plat_app_icon
     *
     * @return the value of tb_promotion.plat_app_icon
     *
     * @mbg.generated
     */
    public String getPlatAppIcon() {
        return platAppIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.plat_app_icon
     *
     * @param platAppIcon the value for tb_promotion.plat_app_icon
     *
     * @mbg.generated
     */
    public void setPlatAppIcon(String platAppIcon) {
        this.platAppIcon = platAppIcon == null ? null : platAppIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.plat_app_name
     *
     * @return the value of tb_promotion.plat_app_name
     *
     * @mbg.generated
     */
    public String getPlatAppName() {
        return platAppName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.plat_app_name
     *
     * @param platAppName the value for tb_promotion.plat_app_name
     *
     * @mbg.generated
     */
    public void setPlatAppName(String platAppName) {
        this.platAppName = platAppName == null ? null : platAppName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.plat_app_package_name
     *
     * @return the value of tb_promotion.plat_app_package_name
     *
     * @mbg.generated
     */
    public String getPlatAppPackageName() {
        return platAppPackageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.plat_app_package_name
     *
     * @param platAppPackageName the value for tb_promotion.plat_app_package_name
     *
     * @mbg.generated
     */
    public void setPlatAppPackageName(String platAppPackageName) {
        this.platAppPackageName = platAppPackageName == null ? null : platAppPackageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.plat_promotion_name
     *
     * @return the value of tb_promotion.plat_promotion_name
     *
     * @mbg.generated
     */
    public String getPlatPromotionName() {
        return platPromotionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.plat_promotion_name
     *
     * @param platPromotionName the value for tb_promotion.plat_promotion_name
     *
     * @mbg.generated
     */
    public void setPlatPromotionName(String platPromotionName) {
        this.platPromotionName = platPromotionName == null ? null : platPromotionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.app_price
     *
     * @return the value of tb_promotion.app_price
     *
     * @mbg.generated
     */
    public BigDecimal getAppPrice() {
        return appPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.app_price
     *
     * @param appPrice the value for tb_promotion.app_price
     *
     * @mbg.generated
     */
    public void setAppPrice(BigDecimal appPrice) {
        this.appPrice = appPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.search_price
     *
     * @return the value of tb_promotion.search_price
     *
     * @mbg.generated
     */
    public BigDecimal getSearchPrice() {
        return searchPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.search_price
     *
     * @param searchPrice the value for tb_promotion.search_price
     *
     * @mbg.generated
     */
    public void setSearchPrice(BigDecimal searchPrice) {
        this.searchPrice = searchPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.star
     *
     * @return the value of tb_promotion.star
     *
     * @mbg.generated
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.star
     *
     * @param star the value for tb_promotion.star
     *
     * @mbg.generated
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.total_limit
     *
     * @return the value of tb_promotion.total_limit
     *
     * @mbg.generated
     */
    public BigDecimal getTotalLimit() {
        return totalLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.total_limit
     *
     * @param totalLimit the value for tb_promotion.total_limit
     *
     * @mbg.generated
     */
    public void setTotalLimit(BigDecimal totalLimit) {
        this.totalLimit = totalLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.app_daily_budget
     *
     * @return the value of tb_promotion.app_daily_budget
     *
     * @mbg.generated
     */
    public BigDecimal getAppDailyBudget() {
        return appDailyBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.app_daily_budget
     *
     * @param appDailyBudget the value for tb_promotion.app_daily_budget
     *
     * @mbg.generated
     */
    public void setAppDailyBudget(BigDecimal appDailyBudget) {
        this.appDailyBudget = appDailyBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.search_daily_budget
     *
     * @return the value of tb_promotion.search_daily_budget
     *
     * @mbg.generated
     */
    public BigDecimal getSearchDailyBudget() {
        return searchDailyBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.search_daily_budget
     *
     * @param searchDailyBudget the value for tb_promotion.search_daily_budget
     *
     * @mbg.generated
     */
    public void setSearchDailyBudget(BigDecimal searchDailyBudget) {
        this.searchDailyBudget = searchDailyBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.app_regular_change_price
     *
     * @return the value of tb_promotion.app_regular_change_price
     *
     * @mbg.generated
     */
    public Byte getAppRegularChangePrice() {
        return appRegularChangePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.app_regular_change_price
     *
     * @param appRegularChangePrice the value for tb_promotion.app_regular_change_price
     *
     * @mbg.generated
     */
    public void setAppRegularChangePrice(Byte appRegularChangePrice) {
        this.appRegularChangePrice = appRegularChangePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.search_regular_change_price
     *
     * @return the value of tb_promotion.search_regular_change_price
     *
     * @mbg.generated
     */
    public Byte getSearchRegularChangePrice() {
        return searchRegularChangePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.search_regular_change_price
     *
     * @param searchRegularChangePrice the value for tb_promotion.search_regular_change_price
     *
     * @mbg.generated
     */
    public void setSearchRegularChangePrice(Byte searchRegularChangePrice) {
        this.searchRegularChangePrice = searchRegularChangePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.status
     *
     * @return the value of tb_promotion.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.status
     *
     * @param status the value for tb_promotion.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.ctime
     *
     * @return the value of tb_promotion.ctime
     *
     * @mbg.generated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.ctime
     *
     * @param ctime the value for tb_promotion.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion.mtime
     *
     * @return the value of tb_promotion.mtime
     *
     * @mbg.generated
     */
    public Integer getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion.mtime
     *
     * @param mtime the value for tb_promotion.mtime
     *
     * @mbg.generated
     */
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }
}