package com.wk.cpd.mvc.dao.model;

import java.math.BigDecimal;

public class PromotionRegularPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.plat_id
     *
     * @mbg.generated
     */
    private Integer platId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.plat_promotion_id
     *
     * @mbg.generated
     */
    private String platPromotionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.price_type
     *
     * @mbg.generated
     */
    private Byte priceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.hour
     *
     * @mbg.generated
     */
    private Byte hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.minute
     *
     * @mbg.generated
     */
    private Byte minute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.monday
     *
     * @mbg.generated
     */
    private Byte monday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.tuesday
     *
     * @mbg.generated
     */
    private Byte tuesday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.wednesday
     *
     * @mbg.generated
     */
    private Byte wednesday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.thursday
     *
     * @mbg.generated
     */
    private Byte thursday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.friday
     *
     * @mbg.generated
     */
    private Byte friday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.saturday
     *
     * @mbg.generated
     */
    private Byte saturday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.sunday
     *
     * @mbg.generated
     */
    private Byte sunday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.ctime
     *
     * @mbg.generated
     */
    private Integer ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_promotion_regular_change_price.mtime
     *
     * @mbg.generated
     */
    private Integer mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.id
     *
     * @return the value of tb_promotion_regular_change_price.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.id
     *
     * @param id the value for tb_promotion_regular_change_price.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.plat_id
     *
     * @return the value of tb_promotion_regular_change_price.plat_id
     *
     * @mbg.generated
     */
    public Integer getPlatId() {
        return platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.plat_id
     *
     * @param platId the value for tb_promotion_regular_change_price.plat_id
     *
     * @mbg.generated
     */
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.plat_promotion_id
     *
     * @return the value of tb_promotion_regular_change_price.plat_promotion_id
     *
     * @mbg.generated
     */
    public String getPlatPromotionId() {
        return platPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.plat_promotion_id
     *
     * @param platPromotionId the value for tb_promotion_regular_change_price.plat_promotion_id
     *
     * @mbg.generated
     */
    public void setPlatPromotionId(String platPromotionId) {
        this.platPromotionId = platPromotionId == null ? null : platPromotionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.type
     *
     * @return the value of tb_promotion_regular_change_price.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.type
     *
     * @param type the value for tb_promotion_regular_change_price.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.price_type
     *
     * @return the value of tb_promotion_regular_change_price.price_type
     *
     * @mbg.generated
     */
    public Byte getPriceType() {
        return priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.price_type
     *
     * @param priceType the value for tb_promotion_regular_change_price.price_type
     *
     * @mbg.generated
     */
    public void setPriceType(Byte priceType) {
        this.priceType = priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.price
     *
     * @return the value of tb_promotion_regular_change_price.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.price
     *
     * @param price the value for tb_promotion_regular_change_price.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.hour
     *
     * @return the value of tb_promotion_regular_change_price.hour
     *
     * @mbg.generated
     */
    public Byte getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.hour
     *
     * @param hour the value for tb_promotion_regular_change_price.hour
     *
     * @mbg.generated
     */
    public void setHour(Byte hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.minute
     *
     * @return the value of tb_promotion_regular_change_price.minute
     *
     * @mbg.generated
     */
    public Byte getMinute() {
        return minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.minute
     *
     * @param minute the value for tb_promotion_regular_change_price.minute
     *
     * @mbg.generated
     */
    public void setMinute(Byte minute) {
        this.minute = minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.monday
     *
     * @return the value of tb_promotion_regular_change_price.monday
     *
     * @mbg.generated
     */
    public Byte getMonday() {
        return monday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.monday
     *
     * @param monday the value for tb_promotion_regular_change_price.monday
     *
     * @mbg.generated
     */
    public void setMonday(Byte monday) {
        this.monday = monday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.tuesday
     *
     * @return the value of tb_promotion_regular_change_price.tuesday
     *
     * @mbg.generated
     */
    public Byte getTuesday() {
        return tuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.tuesday
     *
     * @param tuesday the value for tb_promotion_regular_change_price.tuesday
     *
     * @mbg.generated
     */
    public void setTuesday(Byte tuesday) {
        this.tuesday = tuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.wednesday
     *
     * @return the value of tb_promotion_regular_change_price.wednesday
     *
     * @mbg.generated
     */
    public Byte getWednesday() {
        return wednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.wednesday
     *
     * @param wednesday the value for tb_promotion_regular_change_price.wednesday
     *
     * @mbg.generated
     */
    public void setWednesday(Byte wednesday) {
        this.wednesday = wednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.thursday
     *
     * @return the value of tb_promotion_regular_change_price.thursday
     *
     * @mbg.generated
     */
    public Byte getThursday() {
        return thursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.thursday
     *
     * @param thursday the value for tb_promotion_regular_change_price.thursday
     *
     * @mbg.generated
     */
    public void setThursday(Byte thursday) {
        this.thursday = thursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.friday
     *
     * @return the value of tb_promotion_regular_change_price.friday
     *
     * @mbg.generated
     */
    public Byte getFriday() {
        return friday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.friday
     *
     * @param friday the value for tb_promotion_regular_change_price.friday
     *
     * @mbg.generated
     */
    public void setFriday(Byte friday) {
        this.friday = friday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.saturday
     *
     * @return the value of tb_promotion_regular_change_price.saturday
     *
     * @mbg.generated
     */
    public Byte getSaturday() {
        return saturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.saturday
     *
     * @param saturday the value for tb_promotion_regular_change_price.saturday
     *
     * @mbg.generated
     */
    public void setSaturday(Byte saturday) {
        this.saturday = saturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.sunday
     *
     * @return the value of tb_promotion_regular_change_price.sunday
     *
     * @mbg.generated
     */
    public Byte getSunday() {
        return sunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.sunday
     *
     * @param sunday the value for tb_promotion_regular_change_price.sunday
     *
     * @mbg.generated
     */
    public void setSunday(Byte sunday) {
        this.sunday = sunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.status
     *
     * @return the value of tb_promotion_regular_change_price.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.status
     *
     * @param status the value for tb_promotion_regular_change_price.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.ctime
     *
     * @return the value of tb_promotion_regular_change_price.ctime
     *
     * @mbg.generated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.ctime
     *
     * @param ctime the value for tb_promotion_regular_change_price.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_promotion_regular_change_price.mtime
     *
     * @return the value of tb_promotion_regular_change_price.mtime
     *
     * @mbg.generated
     */
    public Integer getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_promotion_regular_change_price.mtime
     *
     * @param mtime the value for tb_promotion_regular_change_price.mtime
     *
     * @mbg.generated
     */
    public void setMtime(Integer mtime) {
        this.mtime = mtime;
    }
}