package com.wk.cpd.mvc.dao.mapper;

import com.wk.cpd.mvc.dao.model.DspInfo;

public interface DspInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_info
     *
     * @mbg.generated
     */
    int insert(DspInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_info
     *
     * @mbg.generated
     */
    int insertSelective(DspInfo record);
}