package com.wk.cpd.mvc.dao.mapper;

import com.wk.cpd.mvc.dao.model.Plat;

public interface PlatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat
     *
     * @mbg.generated
     */
    int insert(Plat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat
     *
     * @mbg.generated
     */
    int insertSelective(Plat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat
     *
     * @mbg.generated
     */
    Plat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Plat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Plat record);
}