package com.wk.cpd.mvc.dao.mapper;

import com.wk.cpd.mvc.dao.model.PlatUser;

public interface PlatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat_user
     *
     * @mbg.generated
     */
    int insert(PlatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat_user
     *
     * @mbg.generated
     */
    int insertSelective(PlatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat_user
     *
     * @mbg.generated
     */
    PlatUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plat_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlatUser record);
}