package com.wk.cpd.mvc.dao.mapper;

import com.wk.cpd.mvc.dao.model.PromotionMinutelyHistory;

public interface PromotionMinutelyHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_minutely_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_minutely_report
     *
     * @mbg.generated
     */
    int insert(PromotionMinutelyHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_minutely_report
     *
     * @mbg.generated
     */
    int insertSelective(PromotionMinutelyHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_minutely_report
     *
     * @mbg.generated
     */
    PromotionMinutelyHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_minutely_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PromotionMinutelyHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_minutely_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PromotionMinutelyHistory record);
}