package com.wk.cpd.mvc.dao.mapper;

import com.wk.cpd.mvc.dao.model.PromotionPriceHistory;

public interface PromotionPriceHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_price_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_price_log
     *
     * @mbg.generated
     */
    int insert(PromotionPriceHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_price_log
     *
     * @mbg.generated
     */
    int insertSelective(PromotionPriceHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_price_log
     *
     * @mbg.generated
     */
    PromotionPriceHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_price_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PromotionPriceHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion_price_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PromotionPriceHistory record);
}