package com.wk.cpd.mvc.dao.mapper;

import com.wk.cpd.mvc.dao.model.Promotion;

public interface PromotionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion
     *
     * @mbg.generated
     */
    int insert(Promotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion
     *
     * @mbg.generated
     */
    int insertSelective(Promotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion
     *
     * @mbg.generated
     */
    Promotion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Promotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_promotion
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Promotion record);
}